### ISSUE TITLE
NEW FEATURE: Animation support

### ISSUE THREAD

**Issue by MuellerSeb** [psyplot/psy-view#11]
#### Summary
Animation when time axis present.

#### Reason
To compete with ncview, it would be nice to show the time-evolution of a netcdf variable within a mapplot.

#### Detailed explanation
Matplotlib provides animations, so it shouldn't be to hard to make a simple interface like ncview provides, with next/previous frame, play forward/backward and delay.

#### Example
![ncview-example](https://user-images.githubusercontent.com/19690642/70147453-8a5cb300-16a4-11ea-92fe-ccdb4464f3bc.png)

Thanks for the great package!
Cheers, Sebastian

**Comment by Chilipp** [comment]
Hey @MuellerSeb! I finally now work on psy-view, an ncview-like interface to psyplot. Here I also implement these animation features and more. It would be great if you could give it a try. You can either try it in the browser by clicking on [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/Chilipp/psy-view/master?urlpath=%2Fdesktop) or install it on your own machine via conda to test it with your own files (see the [installation instructions](https://github.com/psyplot/psy-view/#installation)). When installed, this widget is also available in the general psyplot-gui.

This package is under heavy development at the moment and not yet in its beta phase, but I am nevertheless highly appreciating any feature requests or bug reports.

**Comment by MuellerSeb** [comment]
Neat! I'll give it a try ;-)

stay healthy!

**Comment by MuellerSeb** [comment]
Looks good! One problem with the animation at this point is, that the colormap boundaries are changing for each time-step. I think, it should be rescaled to use the bounds of the whole time-frame.

**Comment by Chilipp** [comment]
True, I thought about the same. The challenge is to handle very large data files (or remote data files), particularly when the user decides to use percentiles (e.g. the first to 99th percentile) for the colormap boundary, rather than only minimum and maximum. For very large files, one should rather use dask and a distributed processing and I think it's too much to implement such a framework in psyplot just to calculate some colormap boundaries. 

Maybe I'd rather fix the color boundaries when starting the animation and add a formatoption that controls whether the entire data is used, or only the data shown. What do you think about this option?

**Comment by MuellerSeb** [comment]
that sounds good. another option could be to only update the lower/upper bounds if the bounds of the current time-step exceed the current limits.

**Comment by Chilipp** [comment]
The animation is implemented, I am closing this issue here in favor of https://github.com/psyplot/psyplot/issues/21 and https://github.com/psyplot/psy-simple/issues/12 where I will work on the two aspects mentioned in https://github.com/psyplot/psy-view/issues/11#issuecomment-613536436 and https://github.com/psyplot/psy-view/issues/11#issuecomment-613550823.
