### ISSUE TITLE
New Feature: multi-page pdf

### ISSUE THREAD

**Issue by tobstac** [psyplot/psy-view#15]
#### Problem description

Psy-plot support a range of output formats including pdf. However, every panel needs to be exported in a single file.

#### Expected Output
It would be preferable to be able to select panels and export them to a multi-page pdf. It would be even better, if the actual export does not happen when the panel is selected for export, but as a final step. For example, if I prepare several panels and realize with the last one that I forgot something in all the others, I could simply add the information to the still accessible panels, instead of having to reproduce all of them again.

**Comment by Chilipp** [comment]
Hi @tobstac! This is straight-forward in the psyplot-gui (and actually already possible, I can show you how, if you like), but how would that work within the standalone psy-view app? 

In psy-view, you only have one plot per plotmethod (mapplot, plot2d, lineplot, etc.) per dataset (you can open multiple datasets at the same time). I could implement that all open figures are exported to a single multi-page PDF (or you select the open figures), but in this framework, it would not be possible to export plots of different variables (or different dimensions) that are in the same dataset. I.e. neither something like

```
psy-view test.nc
make plot of var1 in test.nc
save plot of var1 to PDF
change to var2 in test.nc
save plot of var2 to PDF
```

nor

```
psy-view test.nc
make plot of var1 in test.nc
save plot of var1 to PDF
change plot to second timestep
save plot of var1 to PDF
```

would work. What I could do, however, is to allow the user to create multiple plots per plotmethod and let the user select which plot he currently wants to modify in the psy-view window. This would not be too complicated to implement (as I already allow one plot per dataset). It would work the same way as with lineplots, where you can currently select which line you want to modify

![Screenshot from 2020-04-17 14-02-27](https://user-images.githubusercontent.com/9960249/79567240-29ae9f80-80b4-11ea-961b-27fe6fce862e.png)

It would anyway be a good idea to implement something like this in order to have the functionality in the psyplot-gui.

What do you think about it?

**Comment by tobstac** [comment]
Ok... sounds interesting. But I don't think I get it completely. How would the multi-page export work in this idea - especially considering the limitations you mentioned above?

**Comment by Chilipp** [comment]
Hmm, shall we make a quick video call? Maybe it's easier to talk about it that way. When would you have a few minutes to discuss this (via [Jitsi](https://meet.jit.si)?)?
